id: I4C497E9B
legacy_id: P007077
ocr_import_info:
  bdrc_scan_id: W19508
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T20:19:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:24:59.287242+00:00'
last_modified: 2022-08-30 23:26:16.291626
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19508
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19508
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡང་ཏི་ནག་པོ་གསེར་གྱི་འབྲུ་གཅིག་པའི་ཆོས་སྐོར།
  author: དུང་མཚོ་རས་པ་ཕྱི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.7458234922695774
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1709:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1709
      total_pages: 519
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1709.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7159844791432605
    legacy_id: v002
  I1708:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1708
      total_pages: 562
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1708.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6951294309981157
    legacy_id: v001
  I1710:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1710
      total_pages: 517
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1710.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8133568391100504
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
