id: I4C497E9B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:22:56+00:00'
last_modified: '2022-06-09T04:37:25.529973+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19508
  title: ཡང་ཏི་ནག་པོ་གསེར་གྱི་འབྲུ་གཅིག་པའི་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3AE5:
      image_group_id: I1708
      title: ''
      total_pages: 562
      order: 1
      base_file: 3AE5.txt
    A951:
      image_group_id: I1709
      title: ''
      total_pages: 519
      order: 2
      base_file: A951.txt
    AA1A:
      image_group_id: I1710
      title: ''
      total_pages: 517
      order: 3
      base_file: AA1A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
